---
types:
 - name: calendary
   version: 1.0
   fields:
    - name: language
      kind: string
      descriptions: :tiun.types.calendary.language
    - name: alphabeth
      kind: string
      descriptions: :tiun.types.calendary.alphabeth
    - name: dictionary_uri
      optional: true
      kind: uri
      descriptions: :tiun.types.calendary.dictionary_uri
    - name: value
      kind: string
      descriptions: :tiun.types.calendary.value
    - name: tags
      kind: string list
      descriptions: :tiun.types.calendary.tags
    - name: meta
      kind: json
      descriptions: :tiun.types.calendary.meta
    - name: kind
      kind: enum <Term, Saying, Interpretation, Idiom>
      descriptions: :tiun.types.calendary.kind
    - name: attitudes
      kind: attitude
      descriptions: :tiun.types.calendary.attitudes
resources:
 - name: calendary.index
   path: /api/v1/calendaries.json
   methods:
    - name: get
      version: 1.0
      kind: calendary page
      descriptions: :tiun.resources.calendary.index.get
      auth: no
      allowed_errors: [200, 206, 416, 422.3, 500]
      args:
       - name: per_page
         kind: natural
         default: 10 
         maximum: 50
         descriptions: :tiun.resources.calendary.index.args.per_page
       - name: page
         kind: natural
         default: 1
         descriptions: :tiun.resources.calendary.index.args.page
       - name: c
         kind: string
         descriptions: :tiun.resources.calendary.index.args.c
       - name: licit
         kind: bool
         descriptions: :tiun.resources.calendary.index.args.licit
defaults:
   poll_frequency: 3600 # 1 hour
   optional: false # used in fields section
   errors:
    - code: 200
      name: :tiun.defaults.errors.200.name
      descriptions: :tiun.defaults.errors.200.description
    - code: 206
      name: :tiun.defaults.errors.206.name
      descriptions: :tiun.defaults.errors.206.description
    - code: 416
      name: :tiun.defaults.errors.416.name
      descriptions: :tiun.defaults.errors.416.description
    - code: 422.3
      name: :tiun.defaults.errors.422.3.name
      descriptions: :tiun.defaults.errors.422.3.description
    - code: 500
      name: :tiun.defaults.errors.500.name
      descriptions: :tiun.defaults.errors.500.description
