---
defaults:
   poll_frequency: 3600 # 1 hour
   optional: false # used in fields section
   errors:
    - code: 200
      name: :tiun.defaults.errors.200.name
      descriptions: :tiun.defaults.errors.200.description
    - code: 206
      name: :tiun.defaults.errors.206.name
      descriptions: :tiun.defaults.errors.206.description
    - code: 416
      name: :tiun.defaults.errors.416.name
      descriptions: :tiun.defaults.errors.416.description
    - code: 422.3
      name: :tiun.defaults.errors.422.3.name
      descriptions: :tiun.defaults.errors.422.3.description
    - code: 500
      name: :tiun.defaults.errors.500.name
      descriptions: :tiun.defaults.errors.500.description
