prepare:
   fetch:
    - url: "https://raw.githubusercontent.com/znamenica/dneslov/136_zUiVBDvH_pdf_calendary_for_time/.rubocop.yml"
      path: ".rubocop.yml"
engines:
   rubocop:
      enabled: true
      checks:
         Layout/IndentationWidth:
            Width: 3
         Layout/LineLength:
            Max: 130
         Lint/AmbiguousOperatorPrecedence: # new in 1.21
            Enabled: false
         Metrics/MethodLength:
            Max: 15
         Metrics/AbcSize:
            Max: 30
         Style/MethodDefParentheses:
            EnforcedStyle: require_no_parentheses
         Style/NegatedIf:
            Enabled: false
         Style/TrailingCommaInHashLiteral:
            Enabled: false
