dist: xenial
language: ruby
postgresql: 9.6.10
rvm:
 - 2.5.5
env:
   global:
    - BUNDLE_JOBS=4
    - RAILS_ENV=test

addons:
   apt_packages:
    - postgresql-contrib-9.6
    - libqtwebkit-dev
    - libqtwebkit4

before_script:
 - createuser -d -l -s -e -U postgres dneslov
 - bundle exec rake db:create db:migrate
 - cp -f config/secret_env.yml config/secrets.yml
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

before_install:

script:
 - bundle exec rake cucumber

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
