import SelectField from 'SelectField'

export default class EventTypeField extends SelectField {
   static defaultProps = {
      name: 'type',
      title: 'Вид события',
      codeNames: {
         '': 'Избери вид события...',
         'Tale': 'Беседа',
         'Battle': 'Битва',
         'Thanksgiving': 'Благодарение',
         'Benediction': 'Благословение',
         'Marriage': 'Брак',
         'Exaltation': 'Воздвижение',
         'Apparation': 'Вид',
         'Ascension': 'Вознесение',
         'SoldierMemory': 'Воинская память',
         'Restoration': 'Восстановление',
         'Resurrection': 'Воскресение',
         'Entrance': 'Вход',
         'Deaconry': 'Дияконство',
         'Enheresment': 'Впадение в ересь',
         'Conception': 'Зачинание',
         'Protection': 'Заступление',
         'Conceiving': 'Зачатие',
         'Portent': 'Знамение',
         'Deliverance': 'Избавление',
         'Betraial': 'Измена',
         'Procession': 'Изнесение',
         'Monasticry': 'Иночество',
         'Hypodeaconry': 'Иподьяконство',
         'Baptism': 'Крещение',
         'Superstructure': 'Надстройка',
         'Writing': 'Написание',
         'Learning': 'Научение',
         'Numbness': 'Онемение',
         'Deposition': 'Низложение',
         'Sanctification': 'Освящение',
         'Uncovering': 'Обретение',
         'Circumcision': 'Обрезание',
         'Revival': 'Оживление',
         'Liberation': 'Освобождение',
         'Renunciation': 'Отречение',
         'Fall': 'Падение',
         'Burial': 'Погребение',
         'GreatFire': 'Пожар',
         'Repentance': 'Покаяние',
         'Rest': 'Покой',
         'Placing': 'Положение',
         'Veneration': 'Почитание',
         'Primacy': 'Предстоятельство',
         'PuttingInAgain': 'Преложение',
         'Teleportation': 'Премещение',
         'Translation': 'Пренесение',
         'Calling': 'Призвание',
         'Captivity': 'Пленение',
         'Adoration': 'Поклонение',
         'Transfiguration': 'Преображение',
         'Curse': 'Проклятие',
         'Preach': 'Проповедание',
         'Prophecy': 'Пророчество',
         'Canonization': 'Прославление',
         'Repose': 'Преставление',
         'Throne': 'Интронизация',
         'Destruction': 'Разрушение',
         'Schism': 'Уход в раскол',
         'Defrocking': 'Извержение из сана',
         'Decanonization': 'Деканонизация',
         'Nativity': 'Рождение',
         'Frockbearing': 'Облечение в рясу',
         'Council': 'Собор',
         'Bishopry': 'Святительство',
         'Priestship': 'Священство',
         'Founding': 'Создание',
         'Hiddening': 'Сокрытие',
         'Phenomenon': 'Появление',
         'Meeting': 'Сретение',
         'Passion': 'Страсти',
         'Schima': 'Схима',
         'Supper': 'Вечеря',
         'Sobriety': 'Трезвение',
         'Labor': 'Труд',
         'Earthquake': 'Землетрясение',
         'Assurance': 'Уверение',
         'Loss': 'Утрата',
         'Glorification': 'Чин прославления',
         'Reader': 'Чтечество',
         'Miracle': 'Чудо',
         'Appearance': 'Явление',
      },
      validations: {
         'Пункт из списка должен быть выбран': /^$/,
      }
   }
}
